include:
- file: composer-package.yml
  project: mageops/gitlab-ci-templates
  ref: master
- file: magesuite-module.yml
  project: magesuite/gitlab-ci-config
  ref: master
- local: .gitlab/csbot.gitlabci.yml
stages:
- build
- codesniffer
